### ISSUE TITLE
Selected hash to generate output or from file to hash

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#30]
I don't know if this is good or bad. I just came up with the idea. If you select as example (0 - MD5) your file will be named md5_found.txt or just 0_found.txt. Or if you save a file as md5_found.txt you're attack hash mode turns automatic to md5.

Or maybe some form of variable that you can set to filenames.

**Comment by s77rt** [comment]
both are not worth it because some hashes types are complicated:

- Juniper/NetBSD sha1crypt
- Open Document Format (ODF) 1.1 (SHA-1, Blowfish)
- md5(sha1($pass).md5($pass).sha1($pass))
- Android FDE <= 4.3

the user is probably never going to set such file names, some are even impossible (due to os filename restrictions)

and the other option to use 0_founds.txt or 2500_founds.txt is kinda confusing: (is there 2500 founds or those are the founds that are related to mode 2500)
can be fixed to use m0_founds.txt and m2500_founds.txt but it's still not worth it and it makes more problems then it solve (what if there is a file with that name, what should we do? append a unique suffix?)

it's just not a good enough solution, better to keep the user manually specify hash type and output file

**Comment by foordeluxe** [comment]
I know about filename restrictions. But hashcatGUI use some form of variables for cracked hashes. So you can set set if you want to save cracked files as starting date, or hash mode. But I guess this will just make people confused, m0 or something could still confuse people. Maybe they think it's how many cracked hashes there is or such. So Yeah I don't think this is a good idea.
