### ISSUE TITLE
Better way to control wordlists

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#5]
Right now you can only add one wordlist at a time. And also clipboard. I have used HashcatGUI before. And what I like in that is that you can choose which wordlist that should be used either first, second or third or much later.

I have Attached a screenshot how I mean. I always sort by size, but that's me.
![HashcatGUI_4A85X1FnKq](https://user-images.githubusercontent.com/68303704/87479967-b671e680-c62c-11ea-8fb4-c0d03e312df6.png)

**Comment by s77rt** [comment]
Hi,
regarding the dictionaries/wordlists selection, currently hashcat.launcher only uses a simple text area, because the ui api that we uses "[fyne](https://github.com/fyne-io/fyne)" does not currently supports the table widget, once it does it will be used and you shall be able to have a better control on wordlists including the sort feature.


"And what I like in that is that you can choose which wordlist that should be used either first, second or third or much later."
I think you meant for different tasks, right?
"You can do that already, you just have to click on the "Launch hashcat !" button and the attack will be queued, if you want to setup a sequence; let's say a (dictionary attack + rules) + (dictionary attack + rules) + (mask attack), just do it and click on the button "Launch hashcat !" and those attacks will start one after another;
Additionally, you can set how many attacks to run at a time, by default it will run only one attack, then after it's finished move to the next one, you can increase that to let's say 2 attacks at a time, by going to Options and change the Max Active Sessions to 2. (also make sure that Auto Session Start is set to Enable)
here is a [demo](https://i.postimg.cc/HWZbb0T5/hashcat-launcher-demo2.gif) ; in this demo i made 3 attacks for one list, and all the attacks were being queued and being processed one after another." quoted from HK forum

**Comment by foordeluxe** [comment]
Thanks for the answer. Didn't know that the ui api didn't accept this. Anyway nice with multiple queued options.

**Comment by s77rt** [comment]
Hi,
you may want to check v0.5.0 it's a bit easier to handle dictionaries now

**Comment by foordeluxe** [comment]
I saw that 5.0.0 can do this now. Thanks so much.
