### ISSUE TITLE
Quit queued items

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#63]
I wonder if there is a way to quit queued items. It was possible in old version.

**Comment by s77rt** [comment]
you can use the Delete button? or you also want to keep .restore file so you can restore it later?

**Comment by foordeluxe** [comment]
Didn't know that you could delete them. Thanks for that information. No I don't need to restore them later.

**Comment by s77rt** [comment]
alright
just to add for further readers, i also think it's pointless to remove them from the queue and keeping the restore file because they will be loaded automatically once you reopen the app again
it's either you delete both task + .restore file or keep both

(in case you really need to only delete the task, a workaround is to make a backup for the .restore file, delete the task (.restore file will be deleted too) and when you feel it's time to get that task back just restore the backed up .restore file)
