### ISSUE TITLE
When trying to import config the window doesn't popup

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#64]
So every time I want to import a config I need to go to the hashcat.launcher icon and select the new window. I don't know why it get placed in the background and not popup in front of me.

**Comment by s77rt** [comment]
i can't replicate this
any chance you can try with another os?

**Comment by foordeluxe** [comment]
Wrong information. This only happen when trying to use output for the tool. The window wont popup.

**Comment by foordeluxe** [comment]
With this said, I mean the window would hide behind the tool/Icon. And not coming up on the screen.

**Comment by s77rt** [comment]
ah okay, that can be expected
hashcat.launcher have two separated parts, frontend and backend that are connected
the output file selection is handled by the backend part, which is sometimes handled by the os as another process that's why the popup is not on top

i had this on windows few times, while on linux always on top, so it's hard to reproduce thus hard to fix

**Comment by foordeluxe** [comment]
Thanks for the information. I saw popup in early alpha and now it's gone. I can live with this.
