### ISSUE TITLE
A way to set a name to each configuration file

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#79]
Right now you can rename each config file so you know which. But sometimes when it's loaded and you look at the current loaded config, there is no indication which config you loaded. It would be nice if you could set a name to each config you save. Which would be easier to remember which one you have loaded.

**Comment by s77rt** [comment]
I don't think this will help the UX much.
However, after you load the config file you will get an alert message: "Imported! (_config file name here_)"

I think that's enough, as the user can still further change the options and it won't make sense to state that "_config file name here_" is loaded because due to changes he may have mode, the options in the config file and the current options may not match.
